using ClosedXML.Excel;
using FluentValidation;
using MediatR;
using TowerOps.Application.Common;
using TowerOps.Domain.Interfaces.Repositories;

namespace TowerOps.Application.Commands.Reports.ExportBDT;

public record ExportBDTCommand : ICommand<byte[]>
{
    public DateTime? FromDateUtc { get; init; }
    public DateTime? ToDateUtc { get; init; }
}

public class ExportBDTCommandValidator : AbstractValidator<ExportBDTCommand>
{
    public ExportBDTCommandValidator()
    {
        RuleFor(x => x)
            .Must(x => !x.FromDateUtc.HasValue || !x.ToDateUtc.HasValue || x.FromDateUtc <= x.ToDateUtc)
            .WithMessage("FromDateUtc must be before or equal to ToDateUtc.");
    }
}

public sealed class ExportBDTCommandHandler : IRequestHandler<ExportBDTCommand, Result<byte[]>>
{
    private readonly IBatteryDischargeTestRepository _batteryDischargeTestRepository;

    public ExportBDTCommandHandler(IBatteryDischargeTestRepository batteryDischargeTestRepository)
    {
        _batteryDischargeTestRepository = batteryDischargeTestRepository;
    }

    public async Task<Result<byte[]>> Handle(ExportBDTCommand request, CancellationToken cancellationToken)
    {
        var all = await _batteryDischargeTestRepository.GetAllAsNoTrackingAsync(cancellationToken);

        var rows = all.AsEnumerable();
        if (request.FromDateUtc.HasValue)
            rows = rows.Where(x => x.TestDateUtc >= request.FromDateUtc.Value);
        if (request.ToDateUtc.HasValue)
            rows = rows.Where(x => x.TestDateUtc <= request.ToDateUtc.Value);

        using var workbook = new XLWorkbook();
        BuildSummarySheet(workbook, rows.ToList());
        BuildTemplateSheet(workbook, "BDT sheet");
        BuildTemplateSheet(workbook, "Power Alarm");
        BuildTemplateSheet(workbook, "Config");

        using var stream = new MemoryStream();
        workbook.SaveAs(stream);
        return Result.Success(stream.ToArray());
    }

    private static void BuildSummarySheet(XLWorkbook workbook, IReadOnlyList<Domain.Entities.BatteryDischargeTests.BatteryDischargeTest> rows)
    {
        var ws = workbook.AddWorksheet("Summary");

        var headers = new[]
        {
            "Week", "Site Name", "Short Code", "On Air Date", "Nodal Degree", "Site Category (Shelter/OD/Grill)",
            "Power Source", "Network", "Rectifier Brand", "Battery Brand", "Battery Volt", "Battery Ampere Hour",
            "Start Volt", "Start Amp", "End Volt", "End Amp", "Discharge time( Mins)", "Reason for Test stop",
            "Test Date", "Reason for Repeated BDT", "Cap request #", "Comment"
        };

        for (var i = 0; i < headers.Length; i++)
            ws.Cell(1, i + 1).Value = headers[i];

        var row = 2;
        foreach (var item in rows)
        {
            ws.Cell(row, 1).Value = item.Week;
            ws.Cell(row, 2).Value = item.SiteCode;
            ws.Cell(row, 3).Value = item.SiteCode;
            ws.Cell(row, 4).Value = item.TestDateUtc;
            ws.Cell(row, 5).Value = item.NodalDegree;
            ws.Cell(row, 6).Value = item.SiteCategory;
            ws.Cell(row, 7).Value = item.PowerSource;
            ws.Cell(row, 8).Value = item.Network;
            ws.Cell(row, 9).Value = item.Network;
            ws.Cell(row, 10).Value = item.Notes;
            ws.Cell(row, 11).Value = item.StartVoltage;
            ws.Cell(row, 12).Value = item.StartAmperage;
            ws.Cell(row, 13).Value = item.StartVoltage;
            ws.Cell(row, 14).Value = item.StartAmperage;
            ws.Cell(row, 15).Value = item.EndVoltage;
            ws.Cell(row, 16).Value = item.EndAmperage;
            ws.Cell(row, 17).Value = item.DischargeTimeMinutes;
            ws.Cell(row, 18).Value = item.ReasonForStop;
            ws.Cell(row, 19).Value = item.TestDateUtc;
            ws.Cell(row, 20).Value = item.ReasonForRepeatedBDT;
            ws.Cell(row, 21).Value = item.CapRequestNumber;
            ws.Cell(row, 22).Value = item.Notes;
            row++;
        }

        ws.Columns().AdjustToContents();
    }

    private static void BuildTemplateSheet(XLWorkbook workbook, string sheetName)
    {
        var ws = workbook.AddWorksheet(sheetName);
        ws.Cell(1, 1).Value = "Generated by TowerOps";
        ws.Cell(2, 1).Value = "Use Summary sheet for structured export data.";
        ws.Columns().AdjustToContents();
    }
}
