#!/usr/bin/env python3
"""Generate a sheet-by-sheet review report for Core Business Definitions workbooks."""
from __future__ import annotations

import json
from pathlib import Path
from typing import Any

try:
    from openpyxl import load_workbook  # type: ignore
except Exception:
    load_workbook = None

REPO = Path(__file__).resolve().parents[1]
DOCS = REPO / "docs"
OUT = DOCS / "Core-Business-Definitions-Workbook-Audit.md"

KEY_COLUMNS = {
    "term": ["term", "definition", "business definition", "name"],
    "owner": ["owner", "responsible", "accountable"],
    "formula": ["formula", "equation", "calculation"],
    "source": ["source", "data source", "system source"],
    "kpi": ["kpi", "metric"],
}


def norm(v: Any) -> str:
    return str(v or "").strip().lower()


def find_workbooks() -> list[Path]:
    return sorted([p for p in DOCS.rglob("*") if p.suffix.lower() in {".xlsx", ".xlsm", ".xls"}])


def header_score(headers: list[str]) -> tuple[int, dict[str, bool]]:
    text = [h.lower().strip() for h in headers if h]
    found = {}
    for key, variants in KEY_COLUMNS.items():
        found[key] = any(any(v in h for v in variants) for h in text)
    score = sum(1 for v in found.values() if v)
    return score, found


def review_sheet(ws) -> dict[str, Any]:
    max_row = ws.max_row or 0
    max_col = ws.max_column or 0
    rows = list(ws.iter_rows(min_row=1, max_row=min(max_row, 6), values_only=True))
    header = [norm(c) for c in (rows[0] if rows else [])]

    score, found = header_score(header)
    issues: list[str] = []

    if max_row <= 1:
        issues.append("Sheet appears empty or header-only")
    if score < 2:
        issues.append("Weak data dictionary structure (missing key columns)")

    # duplicate header check
    clean_header = [h for h in header if h]
    if len(set(clean_header)) != len(clean_header):
        issues.append("Duplicate column names in header")

    # quick formula sanity check
    formula_cells = 0
    for row in ws.iter_rows(min_row=2, max_row=min(max_row, 200), values_only=False):
        for cell in row:
            if isinstance(cell.value, str) and cell.value.startswith("="):
                formula_cells += 1

    return {
        "sheet": ws.title,
        "rows": max_row,
        "cols": max_col,
        "header_match_score": score,
        "header_flags": found,
        "formula_cells_1_200": formula_cells,
        "issues": issues,
    }


def write_report(data: dict[str, Any]) -> None:
    lines: list[str] = []
    lines.append("# Core Business Definitions Workbook Audit")
    lines.append("")
    lines.append("This file is generated by `tools/review_business_definitions.py`.")
    lines.append("")

    if data.get("error"):
        lines.append(f"**Status:** {data['error']}")
        lines.append("")
        OUT.write_text("\n".join(lines), encoding="utf-8")
        return

    workbooks = data.get("workbooks", [])
    lines.append(f"**Workbooks found:** {len(workbooks)}")
    lines.append("")

    for wb in workbooks:
        lines.append(f"## {wb['file']}")
        lines.append("")
        for sh in wb["sheets"]:
            lines.append(f"### Sheet: {sh['sheet']}")
            lines.append(f"- Rows: {sh['rows']}")
            lines.append(f"- Cols: {sh['cols']}")
            lines.append(f"- Header match score: {sh['header_match_score']}/5")
            lines.append(f"- Formula cells (first 200 rows): {sh['formula_cells_1_200']}")
            lines.append(f"- Header flags: `{json.dumps(sh['header_flags'])}`")
            if sh["issues"]:
                for issue in sh["issues"]:
                    lines.append(f"- ⚠️ {issue}")
            else:
                lines.append("- ✅ No obvious structural issues detected")
            lines.append("")

    OUT.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    if load_workbook is None:
        write_report({"error": "openpyxl is not installed in this environment."})
        print(f"Wrote {OUT}")
        return 0

    books = find_workbooks()
    if not books:
        write_report({"error": "No .xlsx/.xlsm/.xls files found under docs/."})
        print(f"Wrote {OUT}")
        return 0

    payload: dict[str, Any] = {"workbooks": []}

    for p in books:
        wb = load_workbook(filename=p, data_only=False, read_only=True)
        sheets = [review_sheet(wb[s]) for s in wb.sheetnames]
        payload["workbooks"].append({"file": str(p.relative_to(REPO)), "sheets": sheets})

    write_report(payload)
    print(f"Wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
